apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: website
rules:
  - apiGroups: [networking.k8s.io] # "" indicates the core API group
    resources: [ingresses]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: website
rules:
  - apiGroups: [networking.k8s.io] # "" indicates the core API group
    resources: [ingresses]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: website
subjects:
  - kind: ServiceAccount
    name: website
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: website
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: website
subjects:
  - kind: ServiceAccount
    name: website
    namespace: home
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: website
