resources:
- k8s/service.yaml
- k8s/deployment.yaml
- k8s/ingress.yaml
- k8s/serviceaccount.yaml
- k8s/rbac.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/goraxe/portal
  newName: ghcr.io/goraxe/portal
  newTag: 1.1.4
- name: ghcr.io/goraxe/website
  newName: ghcr.io/goraxe/website
  newTag: 1.0.0
