#
name: CI

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["feature/*"]
  pull_request:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: .pre-commit-config.yaml
      - uses: asdf-vm/actions/install@v2.2.0
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.1
